-- Postgres bootstrap SQL ownership moved to:
--   news-crawler-db/src/db/postgres/migrations/bootstrap/init-db.sql
--
-- This placeholder preserves the historical copilot-dl-news path only.
-- deploy/docker-compose.yml mounts the DB-module-owned file directly.
-- Do not add executable SQL here.
